<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="131150" started-at="2020-01-19T01:35:43 EET" finished-at="2020-01-19T01:37:54 EET">
    <groups>
    </groups>
    <test name="Default test" duration-ms="131150" started-at="2020-01-19T01:35:43 EET" finished-at="2020-01-19T01:37:54 EET">
      <class name="registration_page_testing.NewTest">
        <test-method status="PASS" signature="init_data()[pri:0, instance:registration_page_testing.NewTest@6536e911]" name="init_data" is-config="true" duration-ms="19690" started-at="2020-01-19T01:35:43 EET" finished-at="2020-01-19T01:36:02 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init_data -->
        <test-method status="PASS" signature="all_valid_data()[pri:0, instance:registration_page_testing.NewTest@6536e911]" name="all_valid_data" duration-ms="12256" started-at="2020-01-19T01:36:03 EET" finished-at="2020-01-19T01:36:15 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- all_valid_data -->
        <test-method status="PASS" signature="end_session()[pri:0, instance:registration_page_testing.NewTest@6536e911]" name="end_session" is-config="true" duration-ms="562" started-at="2020-01-19T01:36:15 EET" finished-at="2020-01-19T01:36:15 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end_session -->
        <test-method status="FAIL" signature="frist_name()[pri:1, instance:registration_page_testing.NewTest@6536e911]" name="frist_name" duration-ms="23150" started-at="2020-01-19T01:36:15 EET" finished-at="2020-01-19T01:36:39 EET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Register] but found [My Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Register] but found [My Account]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at registration_page_testing.NewTest.frist_name(NewTest.java:94)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frist_name -->
        <test-method status="PASS" signature="end_session()[pri:0, instance:registration_page_testing.NewTest@6536e911]" name="end_session" is-config="true" duration-ms="374" started-at="2020-01-19T01:36:39 EET" finished-at="2020-01-19T01:36:39 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end_session -->
        <test-method status="FAIL" signature="last_name_1()[pri:2, instance:registration_page_testing.NewTest@6536e911]" name="last_name_1" duration-ms="24167" started-at="2020-01-19T01:36:39 EET" finished-at="2020-01-19T01:37:03 EET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.phptravels.net/register] but found [https://www.phptravels.net/account/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.phptravels.net/register] but found [https://www.phptravels.net/account/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at registration_page_testing.NewTest.last_name_1(NewTest.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- last_name_1 -->
        <test-method status="PASS" signature="end_session()[pri:0, instance:registration_page_testing.NewTest@6536e911]" name="end_session" is-config="true" duration-ms="309" started-at="2020-01-19T01:37:03 EET" finished-at="2020-01-19T01:37:03 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end_session -->
        <test-method status="FAIL" signature="last_name_2()[pri:3, instance:registration_page_testing.NewTest@6536e911]" name="last_name_2" duration-ms="22624" started-at="2020-01-19T01:37:03 EET" finished-at="2020-01-19T01:37:26 EET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.phptravels.net/register] but found [https://www.phptravels.net/account/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.phptravels.net/register] but found [https://www.phptravels.net/account/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at registration_page_testing.NewTest.last_name_2(NewTest.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- last_name_2 -->
        <test-method status="PASS" signature="end_session()[pri:0, instance:registration_page_testing.NewTest@6536e911]" name="end_session" is-config="true" duration-ms="345" started-at="2020-01-19T01:37:26 EET" finished-at="2020-01-19T01:37:26 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end_session -->
        <test-method status="PASS" signature="check_email()[pri:4, instance:registration_page_testing.NewTest@6536e911]" name="check_email" duration-ms="26289" started-at="2020-01-19T01:37:26 EET" finished-at="2020-01-19T01:37:53 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_email -->
        <test-method status="PASS" signature="end_session()[pri:0, instance:registration_page_testing.NewTest@6536e911]" name="end_session" is-config="true" duration-ms="405" started-at="2020-01-19T01:37:53 EET" finished-at="2020-01-19T01:37:53 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end_session -->
        <test-method status="PASS" signature="terminateBrowser()[pri:0, instance:registration_page_testing.NewTest@6536e911]" name="terminateBrowser" is-config="true" duration-ms="794" started-at="2020-01-19T01:37:53 EET" finished-at="2020-01-19T01:37:54 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
      </class> <!-- registration_page_testing.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
